### ISSUE TITLE
Upload images in different folders

### ISSUE THREAD

**Issue by vitalijalbu** [HaschekSolutions/pictshare#106]
Is it possible to upload images in different folders?
For example I'd like to upload user avatar images in a different folder.
Thanks.

**Comment by chrisiaut** [comment]
Virtual folders or internal ones on the server?

You can add anything you want to the URL and it will still show up the image but I'm not sure what your use case might be

**Comment by vitalijalbu** [comment]
I mean internal folders.

**Comment by chrisiaut** [comment]
Why would you care about where it's stored on the server?

**Comment by vitalijalbu** [comment]
:D I just want to organize images in different folders.
Is it possible ?

**Comment by chrisiaut** [comment]
No, the whole idea of pictshare is that you don't have to manage how images are stored
