### ISSUE TITLE
api/geturl.php doesn't work

### ISSUE THREAD

**Issue by vitalijalbu** [HaschekSolutions/pictshare#107]
Maybe i insert the wrong URL? 
https://pictshare.net/api/geturl.php?url=hfq5d9.png

**Comment by chrisiaut** [comment]
the url parameter needs a URL, not a local hash. So for example

To download an external image: `https://pictshare.net/api/geturl.php?url=https://portal.allianz.at/assets/images/logo-allianz.jpg`
