### ISSUE TITLE
autoupdate should default to off

### ISSUE THREAD

**Issue by sneak** [HaschekSolutions/pictshare#109]
Programs that download and execute new code from the internet are dangerous.   Autoupdate should be opt-in, not opt-out.

**Comment by chrisiaut** [comment]
For most users the security risks from running unpatched code would imho outweigh the risks.

Also: Pictshare doesn't have an auto update feature - But [the docker image](https://github.com/HaschekSolutions/PictShare-Docker) does. You can obviously [turn it off](https://github.com/HaschekSolutions/PictShare-Docker/blob/master/rootfs/pictshare.sh#L72).
