### ISSUE TITLE
where is the dockerfile?

### ISSUE THREAD

**Issue by sneak** [HaschekSolutions/pictshare#110]
I don't see the dockerfile in the repo used to build the images on dockerhub.

**Comment by chrisiaut** [comment]
As stated in the [DOCKER.md](https://github.com/HaschekSolutions/pictshare/blob/master/rtfm/DOCKER.md) file the repo that is linked to docker hub can be found here: https://github.com/HaschekSolutions/PictShare-Docker

You could also have found that repo and the dockerfile by clicking the link in "Source Repository" on Docker Hub -> https://hub.docker.com/r/hascheksolutions/pictshare/
