### ISSUE TITLE
Uploading images directly using curl

### ISSUE THREAD

**Issue by hisacro** [HaschekSolutions/pictshare#114]
I cannot seem to find any resource to do this on pictshare.net.. 
uploading directly from command line and get the link
`curl -F 'image=??' pictshare.net < image_file`

I find it really useful as I always rely on these 
`curl -F 'sprunge=<-' sprunge.us` 
`curl -F 'f:1=<-' ix.io`

pointing to any resource on how to do that will be much appreciated.

**Comment by geek-at** [comment]
you can find the curl upload command [here](https://github.com/HaschekSolutions/pictshare/blob/master/rtfm/INTEGRATIONS.md#upload-from-cli)

**Comment by hisacro** [comment]
adding this just in case if any one don't want to use jq.. 

`curl -s -F "file=@/path/to/file" https://pictshare.net/api/upload.php  |  sed -e 's/,/\n/g; s/\\//g; s/\"/ /g' | grep url | column -t`

output will be
```
url         :  https://pictshare.net/xxx
delete_url  :  https://pictshare.net/delete_xxxx 
```
if the terminal emulator is set to recognize links then clicking can open it in browser.
