### ISSUE TITLE
Generate Last-Modified and ETag headers

### ISSUE THREAD

**Issue by Nutomic** [HaschekSolutions/pictshare#119]
According to the [docs of Pagespeed Insights](https://developers.google.com/speed/docs/insights/LeverageBrowserCaching#recommendations), these headers are vital for browser caching of resources. 

Both of these headers should be pretty easy to generate based on the filesystem. For last-modified, you just need to read the modification time from the filesystem. And for the etag, use something like an sha1sum of the file. 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Etag

**Comment by geek-at** [comment]
Great idea, thanks
