### ISSUE TITLE
Feature request: MINIO, s3 (aws) compatible storage.

### ISSUE THREAD

**Issue by feruzm** [HaschekSolutions/pictshare#122]
Would be great to have support for min.io api, or have migration to/from min.io.

**Comment by geek-at** [comment]
there already is support for minio built-in: https://github.com/HaschekSolutions/pictshare/blob/master/rtfm/CONFIG.md#s3-compatible-storage

Just put in your bucket name, key, sectret and the endpoint is just the URL for your minio instance
