### ISSUE TITLE
404 Error page - on subfolder

### ISSUE THREAD

**Issue by vitalijalbu** [HaschekSolutions/pictshare#123]
I have uploaded and configured the code on a subfolder.
Image is uploading but gives 404 error when trying to get image.

**Comment by naldekhel** [comment]
Hi @vitalijalbu 

Were you able to ever find a solution for this? Am having the same issue, and wondering if there is a work around. 

Thanks

**Comment by vitalijalbu** [comment]
Unforntunately it cannot be fixed, works only on root folder.

**Comment by Blisk** [comment]
why is this that big problem to solver just change path to folder in code???

**Comment by geek-at** [comment]
At the moment only running from a root path is supported
