### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by Blisk** [HaschekSolutions/pictshare#132]
I have installed pictshare on my server all is default I can upload picture I can see it on server but when I click link I get
Not Found
The requested URL /r4mhm4.jpg was not found on this server.

I have checked apache settings 5 times and all is ok and settings are below. What can be wrong?

```
/**
 * All settings that are uncommented are mandatory
 * Others optional
 */

//Use a specific domain for links presented to the user
//Format: https://your.domain.name/
// MUST HAVE TAILING /
define('URL','http://pictshare.mydomain.net/');

//define('JPEG_COMPRESSION', 90);
//define('FFMPEG_BINARY','');
//define('ALT_FOLDER','/ftp/pictshare');
//define('ALLOWED_SUBNET','192.168.0.0/24');

//S3 settings
//
//define('S3_BUCKET','bucketname');
//define('S3_ACCESS_KEY','');
//define('S3_SECRET_KEY','');
//define('S3_ENDPOINT','http://localhost:9000'); //optional, only if you're using S3 compatible storage like Minio
```

**Comment by geek-at** [comment]
can you show me your .htaccess and apache vhost config?

**Comment by Blisk** [comment]
<IfModule mod_rewrite.c>
RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

RewriteRule ^(.*)$ index.php?url=$1 [QSA,PT,L]

</IfModule>


and vhost config
<VirtualHost *:80>
DocumentRoot /var/www/pictshare/
ServerName photobin.mydomain.net
#ServerAlias photobin.mydomain.net
ServerPath /var/www/pictshare

ErrorLog "logs/pictshare.mydomain.net.error_log"
CustomLog "logs/pictshare.mydomain.net.access_log" combined

<Directory "/var/www/pictshare">
 Order allow,deny
  Allow from all
</Directory>


Alias /pictshare "/var/www/pictshare"
<Directory "/var/www/pictshare">
</Directory>
</VirtualHost>

**Comment by geek-at** [comment]
rewrite looks ok but it's probably easier for you to use the docker container
