### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by Blisk** [HaschekSolutions/pictshare#144]
I just setup pictshare, I can upload files and I can see it in folder but when I try to open link I get file not found.
"The requested URL was not found on this server."

I use centos 8 and apache for web server.
And I didn't find any relevant in logs.
any idea?

**Comment by Blisk** [comment]
is this dead?

**Comment by geek-at** [comment]
did you check read permissions?

**Comment by Blisk** [comment]
> did you check read permissions?

yes I did that many times all is apache writable. I think there must be something wrong with link.
because when I try to open link it says "The requested URL was not found on this server."
when I put in that link the whole path of file than it works

**Comment by geek-at** [comment]
sorry but apache is no longer supported. You might want to use the docker image or use nginx
