### ISSUE TITLE
Reason: Unsupported filetype: x-matroska

### ISSUE THREAD

**Issue by pschonmann** [HaschekSolutions/pictshare#148]
Hi, i have enabled video for sharing

define('CONTENTCONTROLLERS','IMAGE,TEXT,VIDEO,URL');

but getting error when i need upload mkv file.

Reason: Unsupported filetype: x-matroska

I cant find in config where to define that mime x-matroska is enabled. I dont need to convert, just share file as is. If browser is capable to play this video, okay, when not, just download file :D

**Comment by pschonmann** [comment]
Another error when upload mp4

Error uploading vokoscreenNG-2023-04-24_18-21-46.mp4
Reason: Unsupported filetype:

**Comment by pschonmann** [comment]
No, im using it as on pure webhosting. MP4 file is
-
pschonmann@E495:~/Videa$ file vokoscreenNG-2023-04-24_18-21-46.mp4 
vokoscreenNG-2023-04-24_18-21-46.mp4: ISO Media, MP4 v2 [ISO 14496-14]
pschonmann@E495:~/Videa$ mediainfo vokoscreenNG-2023-04-24_18-21-46.mp4 
General
Complete name                            : vokoscreenNG-2023-04-24_18-21-46.mp4
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (mp42/mp41/isom/iso2)
File size                                : 2.83 MiB
Duration                                 : 36 s 880 ms
Overall bit rate                         : 644 kb/s
Encoded date                             : UTC 2023-04-24 16:21:46
Tagged date                              : UTC 2023-04-24 16:22:23

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Baseline@L5
Format settings                          : 1 Ref Frames
Format settings, CABAC                   : No
Format settings, Reference frames        : 1 frame
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 36 s 880 ms
Bit rate                                 : 643 kb/s
Nominal bit rate                         : 2 048 kb/s
Maximum bit rate                         : 2 097 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 200 pixels
Display aspect ratio                     : 16:10
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.011
Stream size                              : 2.83 MiB (100%)
Writing library                          : x264 core 163 r3060 5db6aa6
Encoding settings                        : cabac=0 / ref=1 / deblock=1:0:0 / analyse=0x1:0x1 / me=dia / subme=1 / psy=1 / psy_rd=1,00:0,00 / mixed_ref=0 / me_range=16 / chroma_me=1 / trellis=0 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=0 / threads=8 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=0 / weightp=0 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=0 / rc=cbr / mbtree=0 / bitrate=2048 / ratetol=1,0 / qcomp=0,60 / qpmin=17 / qpmax=17 / qpstep=4 / vbv_maxrate=2048 / vbv_bufsize=1228 / nal_hrd=none / filler=0 / ip_ratio=1,40 / aq=1:1,00
Encoded date                             : UTC 2023-04-24 16:21:46
Tagged date                              : UTC 2023-04-24 16:22:23
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : avcC

**Comment by geek-at** [comment]
could you spin up the official docker container and confirm that it's also not working? Because if it works with docker you might be missing some tools

**Comment by pschonmann** [comment]
Oh, FFMPEG_BINARY wasnt defined.
