### ISSUE TITLE
Is it possible to add authentication only for uploading?

### ISSUE THREAD

**Issue by yusi1** [HaschekSolutions/pictshare#160]
I recently read this: https://www.bbc.co.uk/news/technology-44525358 and thought this could be prevented by adding authentication only for uploading images, and viewing images wouldn't need authentication. 

Is this currently possible? Thank you.

**Comment by geek-at** [comment]
Yes this is possible using the [UPLOAD_CODE](https://github.com/HaschekSolutions/pictshare/blob/master/rtfm/CONFIG.md) config option
