### ISSUE TITLE
add some kind of identifier into every image to make it trackable

### ISSUE THREAD

**Issue by chrisiaut** [HaschekSolutions/pictshare#52]
some off bits or so. needs more research

**Comment by mro** [comment]
visible or https://en.wikipedia.org/wiki/Steganography ?

**Comment by chrisiaut** [comment]
definitley stenography like.

Something like the following where admins can configure a string that is appended to all images so they can check if it was used from their host: http://thedebuggers.com/image-steganography-hiding-text-using-php/
