### ISSUE TITLE
Can't Get MP4s to upload to self hosted Site

### ISSUE THREAD

**Issue by kanelarrete** [HaschekSolutions/pictshare#75]
Hello,

I am running into a problem with a self hosted version of this web app. I have followed the directions as listed out but cannot seem to get mp4s to properly upload to the site. Pictures upload fine. I have checked error logs for apache when I upload (and set log level to debug) and nothing is produced when it finishes uploading. It will go straight back to the home page.

Any ideas? 

Thanks!

**Comment by chrisiaut** [comment]
Hello! sounds like your system cant run  the ffmpeg located in the bin directory.

What OS and Device are you running on?

**Comment by kanelarrete** [comment]
I am running it in a lxc container (Proxmox hypervisor) running Ubuntu
18.04. I can run ffmpeg manually with switches etc but it doesn't seem to
engage from the site.

One thing I have not tried yet though was spinning up a VM with docker
version and see if I get the same problem. I expect that to work though
just due to docker being able to build the exact environment it needs.

**Comment by chrisiaut** [comment]
wow strange .. have you tried the docker container yet?
