### ISSUE TITLE
Include caching headers when serving image files

### ISSUE THREAD

**Issue by thomasjsn** [HaschekSolutions/pictshare#85]
It would be beneficial if caching headers were part of the response when serving image files;

    Cache-control: public, max-age=31536000

As these files should be pretty much immutable. I can submit a pull request for this, if you point me to suitable method where this should be handles.

**Comment by thomasjsn** [comment]
Ok, just an update, I added the following in my nginx config to set caching headers for images and videos.

```
    location ~ \.php {
        fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_script_name;

        if ($request_uri ~ \.(?:ico|gif|jpe?g|png|webp|bmp|mp4)$) {
            add_header Cache-Control "public";
            expires max;
        }   
    }   
```

Maybe just include this in the documentation and leave setting the cache headers out of the php code?

**Comment by dessalines** [comment]
Would be good to add this to the nginx config [here](https://github.com/HaschekSolutions/pictshare/blob/master/rtfm/INSTALL.md)

**Comment by dessalines** [comment]
I've found that I can't get this working with docker and a proxy_pass. Been trying things like a proxy_cache for a few hours...

**Comment by dessalines** [comment]
These are the only headers pictshare is returning when using the proxy_pass with docker:

```
{"name":"content-type","value":"image/png"},
{"name":"date","value":"Sun, 08 Sep 2019 19:58:33 GMT"}
"name":"server","value":"nginx"},
{"name":"X-Firefox-Spdy","value":"h2"}]}}
```

Its missing etag, cache-control, age

**Comment by chrisiaut** [comment]
My idea was that your reverse proxy can manage the cache. I didn't include it in the actual image because caching could have the unwanted side effect that it will be still accessible after you deleted it

**Comment by dessalines** [comment]
Unfortunately the reverse proxy can't do the caching, it needs to be done in the actual docker nginx config.

**Comment by dessalines** [comment]
I'm still stuck on this, has anyone gotten pictshare caching to work?

**Comment by Nutomic** [comment]
FYI you can do this with the following nginx config:
```
if ($request_uri ~ \.(?:ico|gif|jpe?g|png|webp|bmp|mp4)$) {
    add_header Cache-Control "public, max-age=31536000, immutable";
}   
```
