### ISSUE TITLE
MP4 Preview Thumbnail

### ISSUE THREAD

**Issue by sohutek** [HaschekSolutions/pictshare#88]
How can i get thumbnail url of my uploaded mp4 video? I know there is thing called "Preview image generation". But i'm stucking in handling what to do with it from client. Thanks for all your helps.

**Comment by chrisiaut** [comment]
You get the thumbnail of a video by adding "preview" somewhere in the url like so:

Video: https://pictshare.net/ac52m4.mp4
Thumbnail: https://pictshare.net/preview/ac52m4.mp4

Thumbnail is always the same size as the video itself and always takes the first frame of the video
