### ISSUE TITLE
nsupported filetype: octet-stream

### ISSUE THREAD

**Issue by hlwojiv** [HaschekSolutions/pictshare#89]
![image](https://user-images.githubusercontent.com/26682806/60075351-aeac7f00-9757-11e9-8d82-32a2dd47b93c.png)

**Comment by hlwojiv** [comment]
[25-Jun-2019 07:57:07] WARNING: [pool www] child 20 said into stderr: "sh: file: not found"

**Comment by chrisiaut** [comment]
Are you running the docker container?

**Comment by hlwojiv** [comment]
> Are you running the docker container?

yeah, and it doesn't work now.

**Comment by chrisiaut** [comment]
Cannot confirm.

I tested the current image with this command:

`docker run -it --rm -p 89:80 -e "URL=http://localhost:89/" hascheksolutions/pictshare`

then went to [http://localhost:89](http://localhost:89) and I was able to upload PNGs and JPGs and everything just fine.

If you aren't using alpine make sure you have the "file" command installed
