### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by MachineGalaxy** [HaschekSolutions/pictshare#90]
When I upload any file, it uploads successfully however when I try and load the image on the website. The link gives me a 404 error. Have I missed something in the installation to tell it the correct URL or am I just missing something?
```
config.inc.php:
<?php 
/**
 * All settings that are uncommented are mandatory
 * Others optional
 */

//Use a specific domain for links presented to the user
//Format: https://your.domain.name/
// MUST HAVE TAILING /
define('URL','https://img.serenitylabs.co.uk/');
define('LOG_UPLOADER', true);
define('TITLE', 'Serenity Labs Media Uploader');

//define('JPEG_COMPRESSION', 90);
//define('FFMPEG_BINARY','');
//define('ALT_FOLDER','/ftp/pictshare');
//define('ALLOWED_SUBNET','192.168.0.0/24');
```

**Comment by chrisiaut** [comment]
Are you using the docker image or on your own server?

If it's on your own check:

- Your error log
- Is the data folder writeable for the user of the webserver (probably www-data)?

**Comment by MachineGalaxy** [comment]
Hi, 
Don't worry about it. I figured it out. For some reason, my https redirect was not working correctly and that was what was breaking everything. Thanks for the reply though.

Thanks
Zak
