### ISSUE TITLE
Front end?

### ISSUE THREAD

**Issue by dessalines** [HaschekSolutions/pictshare#94]
@chrisiaut if you like, I'd be willing to build a really lean front end for this, in inferno (a tiny react front end). You can look at my other projects such as torrents.csv , or lemmy to see my other work. It wouldn't take me long, there is only 2 pages after all. It'd be responsive and under probably 40 kb.

I might build one anyway, but I wanted to get your input on possibly merging it if you like it, as it'd be responsive and lean.

**Comment by chrisiaut** [comment]
Hey! Sure always looking for improvements

**Comment by dessalines** [comment]
Cool! After i get done with some dev on a few of the things I've been working on, I'll start this.
