### ISSUE TITLE
Image uniqueness / perceptual hash

### ISSUE THREAD

**Issue by dessalines** [HaschekSolutions/pictshare#96]
I assume that pictshare uses a simple md5 or sha hash of the file upload to determine image uniqueness, but it would be really cool if it used an image hash / perceptual hash for uniqueness. 

Here's a good php library:

https://github.com/jenssegers/imagehash

**Comment by chrisiaut** [comment]
interesting thought, will check it out

**Comment by chrisiaut** [comment]
Thought about it and I don't like it because that could mean that a slightls cropped image would get the same hash.
